### PR TITLE
[devops/generation] added working directory setting to sharpmake

### PR DESCRIPTION
**Pull request by RisingLiberty**

### CODE REVIEW

**Review by Dyronix — COMMENTED** [review]
Why was this added?

**Comment by RisingLiberty** [comment]
It's to set the working dir to a certain directory that's well defined

**Comment by RisingLiberty** [comment]
the project location so .rex/build/vs/<projectname>

**Comment by Dyronix** [comment]
And we need this because?

**Comment by RisingLiberty** [comment]
it's a start for when we have the filesystem and start loading files

**Review by Dyronix — APPROVED** [review]

**Pull request merged**
